##  Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8082
  connection-timeout: 5000ms
  servlet:
    context-path: /manager   #项目访问路径

spring:
  # 环境 dev|test|prod   开发环境|测试环境|生产环境
  profiles:
    active: dev
  #  datasource:
#    url: jdbc:mysql://192.168.1.18:3306/xinjue?useOldAliasMetadataBehavior=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
#    driver-class-name: com.mysql.jdbc.Driver
#    password: xinjue  #用户名
#    username: xinjue #密码
#  resources:
#    static-locations: classpath:templates/,classpath:static/ #静态资源 页面 css 图片 js
  ## 下面是整合freemarker start
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      boolean_format: true,false
      whitespace_stripping: true
      default_encoding: UTF-8
      tag_syntax: auto_detect
      url_escaping_charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

## 下面是整合freemarker  end

## 下面是整合mybatis start
mybatis:
  type-aliases-package: com.demo.meta,com.demo.vo
  mapper-locations: classpath:mapper/*.xml
  #配置打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
## 下面是整合mybatis end

## 配置打印sql语句  com.demo.dao是你的接口路径
logging:
  level:
    com.demo.dao : debug
###### 配置分页插件
#pagehelper:
#  dialect: mysql
#  params: countSql
#  reasonable: true
#  support-methods-arguments: true


